[project]
name = "devops-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]",
    "requests>=2.32.3",
]

[tool.uv.sources]
fastmcp = { git = "https://github.com/jlowin/fastmcp.git" }
