services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    user: "0:0"
    environment:
      - env=dev
    volumes:
      - ./config/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  