---
apiVersion: v1
kind: Service
metadata:
  name: devops-mcp
  namespace: devops
  labels:
    app: devops-mcp
spec:
  selector:
    app: devops-mcp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP